### ISSUE TITLE
Plugin encore fonctionnel ?

### ISSUE THREAD

**Issue by Sh1n1x** [QuentinCG/jarvis-fb-messenger#10]
Hello, merci pour ton super plugin ! Je n'arrive pas du tout à le faire fonctionner il me dit que mon login / pass est pas correct alors que si (j'ai retesté en navigation privée pour être sûr). Voici mes logs 
```
INFO:snowboy:Ticks: [2, 20, 5, -1]
DEBUG:root:Initializing Facebook messenger server with email 'contact@xxx.com', getId='False', verbose='True',  mute='True', allowAll='False' and allowedList='['10XXX']'.
Logging in contact@xxx.com...
INFO:client:Logging in contact@xxx.com...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): m.facebook.com
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /?__req=1&seq=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "POST /login.php?login_attempt=1 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /login/save-device/?login_source=login&refsrc=https%3A%2F%2Fwww.facebook.com%2F&_rdr HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /login/save-device/cancel/ HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /home.php?_rdr HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /gettingstarted/?_rdr HTTP/1.1" 200 None
Attempt #1 failed, retrying
WARNING:client:Attempt #1 failed, retrying
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /?__req=3&seq=0 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /gettingstarted/?__req=3&_rdr HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "POST /login.php?login_attempt=1 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /home.php?_rdr HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /gettingstarted/?_rdr HTTP/1.1" 200 None
Attempt #2 failed, retrying
WARNING:client:Attempt #2 failed, retrying
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /?__req=5&seq=0 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /gettingstarted/?__req=5&_rdr HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "POST /login.php?login_attempt=1 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /home.php?_rdr HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /gettingstarted/?_rdr HTTP/1.1" 200 None
Attempt #3 failed, retrying
WARNING:client:Attempt #3 failed, retrying
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /?__req=7&seq=0 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /gettingstarted/?__req=7&_rdr HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "POST /login.php?login_attempt=1 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /home.php?_rdr HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /gettingstarted/?_rdr HTTP/1.1" 200 None
Attempt #4 failed, retrying
WARNING:client:Attempt #4 failed, retrying
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /?__req=9&seq=0 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /gettingstarted/?__req=9&_rdr HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "POST /login.php?login_attempt=1 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /home.php?_rdr HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /gettingstarted/?_rdr HTTP/1.1" 200 None
Attempt #5 failed
WARNING:client:Attempt #5 failed
ERROR:root:Login failed, check email/password.

```

**Comment by QuentinCG** [comment]
Bonjour,

De nombreux utilisateurs arrivent à utiliser ce plugin (encore actuellement).
Pourriez vous réinstaller le plugin et poster ici votre fichier `config.sh` (sans le login et le mot de passe)?

Autre possibilité: Êtes vous sur un réseau restreint qui empêche facebook de fonctionner? (réseau d'entreprise, réseau d'école, ...)

**Comment by QuentinCG** [comment]
Par manque de réponse de votre part, je clos le sujet.

**Comment by ocseb86** [comment]
Bonjour!
J'ai le même problème:
INFO:snowboy:Ticks: [-1, -1, -1, -1]
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /?__req=3&seq=0 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /gettingstarted/?__req=3&_rdr HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "POST /login.php?login_attempt=1 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /home.php?_rdr HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /gettingstarted/?_rdr HTTP/1.1" 200 None
Attempt #2 failed, retrying
WARNING:client:Attempt #2 failed, retrying
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /?__req=5&seq=0 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /gettingstarted/?__req=5&_rdr HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "POST /login.php?login_attempt=1 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /home.php?_rdr HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /gettingstarted/?_rdr HTTP/1.1" 200 None
Attempt #3 failed, retrying
WARNING:client:Attempt #3 failed, retrying
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /?__req=7&seq=0 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /gettingstarted/?__req=7&_rdr HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "POST /login.php?login_attempt=1 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /home.php?_rdr HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /gettingstarted/?_rdr HTTP/1.1" 200 None
Attempt #4 failed, retrying
WARNING:client:Attempt #4 failed, retrying
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /?__req=9&seq=0 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /gettingstarted/?__req=9&_rdr HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "POST /login.php?login_attempt=1 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /home.php?_rdr HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /gettingstarted/?_rdr HTTP/1.1" 200 None
Attempt #5 failed
WARNING:client:Attempt #5 failed
ERROR:root:Login failed, check email/password.
INFO:snowboy:Keyword 1 detected at time: 2019-02-05 11:19:43
DEBUG: modelid=0


Mon fichier config.sh:

# Base configuration (mandatory)
var_jv_pg_fb_email="#######@####.com" # Facebook email used as username (used by Jarvis to send/receive messages/image)
var_jv_pg_fb_password="############" # Facebook password

# Security configuration
var_jv_pg_fb_allow_control_to_all="False" # Allow all people to control Jarvis (True/False)
var_jv_pg_fb_allowed_people_ids="[\"id_1_here\", \"id_2_here\", \"id_3_here\", \"...\"]" # List of allowed people (facebook IDs) to control Jarvis

# Used to send a messenger message from the command file or an other plugin (not needed for basic use of this plugin)
var_jv_pg_fb_main_receiver_id="YOUR RECEIVER ID HERE" # User which will receive message from Jarvis (if configured in command file or in other plugin with this key)
var_jv_pg_fb_main_receiver_name="YOUR RECEIVER NAME HERE"

# Optional configuration
var_jv_pg_fb_mute="True" # Speak with Jarvis without sound (True/False)
var_jv_pg_fb_getId="False" # Send sender ID back to user which sent a message (useful to get list of people to allow later with var_jv_pg_fb_allowed_people_ids)

L'installation etc tout va bien, quand j'essaye d'envoyer un message à ce compte, je n'ai rien en retour, alors que la config devrait lui faire transmettre la "non-autorisation" avec l'id...
Et là non, mon compte perso envoi bien le message, quand je verifie sur le compte du plugin, il l'a bien reçu, mais il n'y a rien dautre, ce qui je suppose, est logique vu qu'il n'arrive pas à se connecter...

j'ai déjà tenter la desinstallation et reinstallation, la mise à jour, je suis sur reseau privé sans restriction facebook, j'ai suivi le fichier install de long en large, (très peu de fichier manquants d'ailleurs donc rapide) mais rien... Il ne veut pas se connecter...

Merci de votre aide!

**Comment by QuentinCG** [comment]
Je vais regarder ça dans la semaine.

Pour information : 
Cela peut venir de plusieurs choses:
 - problème de configuration (dans ce cas je mettrai à jour le fichier de config pour le rendre plus clair pour une utilisation standard)
 - La lib python pour communiquer avec  fb qui n'est pas à jour (je modifierai le plugin en conséquence si c'est le cas).
 - L'installation du plugin s'est mal déroulé (dans ce cas, il faudra voir pourquoi).

**Comment by ocseb86** [comment]
Alors voilà, j'avoue, je plannais... Je n'avais pas validé mon compte depuis la boîte mail... Donc il se connecte depuis jarvis, tout va bien de ce côté là...
Par contre, il ne me renvoi toujours pas de message erreur avec l'id du sender (j'ai modifié le config.sh pour qu'il l'envoi).

**Comment by QuentinCG** [comment]
As tu pensé à mettre cela à True et non False ?

`var_jv_pg_fb_getId="True" # Send sender ID back to user which sent a message (useful to get list of people to allow later with var_jv_pg_fb_allowed_people_ids)`

(je vais mettre à jour le fichier de config pour que ce soit la valeur par défaut)

**Comment by ocseb86** [comment]
Oui oui justement je l'ai vu après coup, je l'ai modifié mais toujours rien...

**Comment by ocseb86** [comment]
Après le choix de l'option n'est pas à retirer selon moi, au contraire c'est une bonne chose. Mais par contre d'où vient l'erreur, bonne question... 🤔

**Comment by QuentinCG** [comment]
As-tu des logs d'erreur ? (car les logs que tu as posté sont obsolètes je pense)
Ca m'aidera à mieux comprendre ce qu'il se passe ;)

> Après le choix de l'option n'est pas à retirer selon moi, au contraire c'est une bonne chose. Mais par contre d'où vient l'erreur, bonne question...

Oui, je vais juste mettre par défaut à True au lieu de False ;)

**Comment by ocseb86** [comment]
Je suis au taf là donc je te confirmerai ça ce soir. Mais de mémoire pas de logs erreurs, la connexion au compte se fait etc. Mais pas de retour d'id...

Merci de tes réponses en tout cas.

**Comment by QuentinCG** [comment]
Note: il est préférable d'être ami avec ton "compte Jarvis" sur fb pour voir les messages qu'il envoie.

**Comment by ocseb86** [comment]
Je regarde ça en rentrant ce soir. Et je te renverrai les logs voir si il y a qqchose.

**Comment by ocseb86** [comment]
J'ai ajouté mon compte Jarvis comme ami mais toujours pas de réponse. Il faut peut être que jarvis soit allumé pour que la réponse soit faite... Bon je crois que je vais vraiment devoir attendre ce soir d'être rentré lol

**Comment by QuentinCG** [comment]
Il faut en effet que Jarvis soit lancé sur ta raspberry pi (ou autre) pour que cela fonctionne sinon le script du plugin ne sera pas actif.

**Comment by ocseb86** [comment]
Trop cool ! J'ai réussi à connecter mon compte et ça fonctionne ! Merci de ton aide.

Il me reste un dernier petit souci, quand je lui demande une réponse qu'il me fait en plusieurs messages, il ne me donne que la première ligne. Je m'explique :

Moi: lis la liste de course
Jarvis: elle contient
.... 

Et la plus rien, le plugin me donnant chaque élément un par un et en un message à la fois... Il y aurait-il une solution pour que tu l'autorise à répondre plusieurs messages à la suite ?

**Comment by QuentinCG** [comment]
Bonne nouvelle :)

Pourrais tu mettre un `jv_pg_fb_start -v` à la place de `jv_pg_fb_start` dans `{le dossier du plugin}/hooks/program_startup` pour voir ce qu'il se passe quand tu redemande tes course ?

Si tu reçois toutes tes courses, c'est que mon plugin est en tord.
Si tu ne reçois pas toutes tes courses, c'est que le mode "json" fait par le concepteur de jarvis ne permet pas ce cas et qu'il faut repenser le plugin de courses pour tout renvoyer en une fois plutôt que réponse par réponse...

Autre moyen de tester sans passer par mon plugin si jamais tu dois faire une demande au niveau de l'autre plugin : `jarvis -j -m -v "lis la liste de course"`.
Ce que tu verras est ce que mon plugin reçoit et ce que n'importe quelle "interface" telle que l'appli android ou autre recevra.

**Comment by QuentinCG** [comment]
(missclick pour le "close")

**Comment by ocseb86** [comment]
bon effectivement je vais devoir modifier le plugin de courses...

Mais bon le reste fonctionne parfaitement et je te remercie de ton aide si rapide!

**Comment by QuentinCG** [comment]
Parfait ;)

Merci à toi, ça m'a permis de me motiver à mettre à jour le guide d'installation et la liste des potentielles erreurs qui peuvent arriver (et comment les corriger) dans le README du projet ;)
