### ISSUE TITLE
Filter warnings and display only answer in Jarvis' JSON

### ISSUE THREAD

**Issue by Oliv4945** [QuentinCG/jarvis-fb-messenger#11]
Hi Quentin,

@fredericsuretat opened [this issue](https://github.com/alexylem/jarvis/issues/774#issuecomment-355588348) to complain about warnings displayed in the app.
Could you please filter on 'keys' in "non verbose" mode [here](https://github.com/QuentinCG/jarvis-fb-messenger/blob/master/script/facebook_server.py#L114), in order to display only "answer" field ?

Something like this :-)
```
            if self.verbose_mode:
              response_to_send += "{}: {}".format(str(key), str(value))
            else:
              if str( key ) == 'answer':
                response_to_send += str(value)
```

Exemple of answer:
```
{
  "warning": "No mic configured, forcing keyboard mode",
  "warning": "No speaker configured, forcing mute",
  "answer":  "ça fonctionne"
}
```

**Comment by QuentinCG** [comment]
@fredericsuretat Could you please update your plugin and tell me if it works now?
(I integrated the fix suggested by @Oliv4945)

@Oliv4945 Thanks for the bugfix suggestion ;)

**Comment by Oliv4945** [comment]
Pretty fast :)
I had the same in the Android app two days ago

**Comment by fredericsuretat** [comment]
hi.it works good. but not the help command :-( sorry.

**Comment by Oliv4945** [comment]
@QuentinCG : I just recorded the following, seems to be fun :p 

```
[  
   {  
      "info":"User defined commands:"
   },
   {  
      "debug":"*AIDE*            *BONJOUR*|*SALUT*    *COMMENT*APPELLE*\n*MERCI*            *AU REVOIR*|*BYE*    ANNULE*|TERMINE*\nENCORE*            *TEST*            *VERSION*\n*REPETE (*) ET (*)    *CA VA*            >*OUI*\n>*NON*|*PAS*"
   },
   {  
      "info":"Commands from plugin jarvis-api:"
   },
   {  
      "debug":""
   },
   {  
      "info":"Commands from plugin jarvis-ui:"
   },
   {  
      "debug":"*OUVR*INTERFACE*"
   }
]
```

**Comment by QuentinCG** [comment]
@Oliv4945 Thanks.
@fredericsuretat It should be fully functional now ;) (I'll close the issue when you confirm it's working)

**Comment by fredericsuretat** [comment]
Hi, I just tested the case, it's better but i have a mistake when i use the word "info" in your plugin : "Réponse non valide".
Other commands or OK.
But I think we are on the good way :-)

**Comment by QuentinCG** [comment]
@fredericsuretat 
Do you have the full logs?
Your error is strange: I don't understand from where this "Réponse non valide" comes from (I have no reference of this sentence in the plugin).

**Comment by fredericsuretat** [comment]
Oh sorry, my bad, This error is on jarvis on android, not in facebook plugin.
It works fine now with your app ....

**Comment by QuentinCG** [comment]
Perfect !
Thanks for your report and for your help.

I close the issue.
