### ISSUE TITLE
erreur sur login

### ISSUE THREAD

**Issue by polbru40** [QuentinCG/jarvis-fb-messenger#5]
J'arrive pas a configurer le plugin. J'ai créé une page facebook, j'ai spécifié dans le fichier de configuration l'adresse émail et le mot passe. Pour le reste je ne vois pas se que je dois mettre. Je met si dessous se que je reçois sur le terminal et je comprends pas pourquoi j'ai l'erreur sur le login ?

jarvis: Bonjour monsieur
DEBUG:root:Initializing Facebook messenger server with email 'anneberthol1977@gmail.com', getId='False', verbose='True', mute='True', allowAll='False' and allowedList='['id_1_here', 'id_2_here', 'id_3_here', '...']'.
ERROR:root:Login failed, check email/password.
WARNING:root:Facebook Messenger server crashed. Restarting...
Traceback (most recent call last):
File "/home/pi/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 160, in
jarvis_fb_server.listen()
File "/usr/local/lib/python3.4/dist-packages/fbchat/client.py", line 935, in listen
self.startListening()
File "/usr/local/lib/python3.4/dist-packages/fbchat/client.py", line 911, in startListening
self.sticky, self.pool = self._getSticky()
File "/usr/local/lib/python3.4/dist-packages/fbchat/client.py", line 740, in _getSticky
"channel": self.user_channel,
AttributeError: 'JarvisFacebookMessengerServer' object has no attribute 'user_channel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/pi/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 170, in
jarvis_fb_server.stop_listening()
AttributeError: 'JarvisFacebookMessengerServer' object has no attribute 'stop_listening'

**Comment by QuentinCG** [comment]
> J'ai créé une page facebook

Il faut creer un compte facebook, pas une page. Je pense que c'est ce que tu as fait ?
Peux tu te connecter sur ton compte facebook via un navigateur web? (pour valider le login/mot de passe)

Si cela ne fonctionne pas: Peux tu modifier les lignes 18 à 22 du fichier jarvis/plugins_installed/jarvis-fb-messenger/script/facebook_server.py
_try:
  fbchat.Client.__init__(self, email, password, verbose)
except Exception:
  logging.error("Login failed, check email/password.")_

PAR

_fbchat.Client.__init__(self, email, password, verbose)_

...et me donner les logs quand tu lance Jarvis?

**Comment by QuentinCG** [comment]
J'arrive à reproduire l'erreur, je vais regarder ca de plus près.

**Comment by QuentinCG** [comment]
Le bug est lié à celui-ci (je te tiens au courant): https://github.com/carpedm20/fbchat/issues/146

**Comment by QuentinCG** [comment]
Lance cette commande, elle résoudra ton problème (je viens de tester):
`sudo pip3 install fbchat==0.9.0`

Je vais ajouter la modif dans le plugin pour que l'on se prémunisse de ce genre de désagrément ;)

Désolé pour la gène occasionnée.
