### ISSUE TITLE
Installed, configured but getting errors on first run.

### ISSUE THREAD

**Issue by zacharisharris** [QuentinCG/jarvis-fb-messenger#6]
I have installed sucessfully, I have configured entering my Jarvis's FB mail & password but when I start Jarvis I get errors. And when I send messages to it on Facebook I get no reply. Why is that? Is it working as expected?

The output when I start Jarvis is this:
```
Traceback (most recent call last):
  File "/home/pi/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 10, in <module>
    import fbchat # Use facebook messenger library
  File "/usr/local/lib/python3.4/dist-packages/fbchat/__init__.py", line 14, in <module>
    from .client import *
  File "/usr/local/lib/python3.4/dist-packages/fbchat/client.py", line 20, in <module>
    from bs4 import BeautifulSoup as bs
ImportError: No module named 'bs4'
./jarvis.sh: line 407: false_STT: command not found
./jarvis.sh: line 407: false_STT: command not found
```

**Edit 1: I have installed BeautifulSoup4 but nothing changed.**
**Edit 2: I am running Jarvis on Rpi 2.**

**Comment by QuentinCG** [comment]
Could you install BeautifulSoup4 for python3?
`sudo pip3 install beautifulsoup4` <-- Not pip but pip3 ! (or `sudo pip3 install bs4`)

If it still doesn't work:
`sudo apt-get install python3-bs4`

If something fixed your issue, I'll add this line to the install.sh file...

**Comment by QuentinCG** [comment]
I did some fix on the install, could you re-install the plugin and give the logs?

I tried the current plugin with fresh raspbian (RPI3) and Debian VM and it worked properly...

**Comment by QuentinCG** [comment]
Could you confirm this is now working ?

There were some issue with some python lib I used.
It would be wise you re-install this plugin in order to have a "clean install".
